#!/usr/bin/env python
"""
Controller for various ports operations
"""
from port import ports, Port
from queue import ports_queue

import make, port
make.pre_cmd = ['echo']
port.port_filter = Port.OLDER

print "Getting 'x11/xorg' dependant handler..."
ports['x11/xorg'].depends()

#ports_queue.join()

for name, port in ports.iteritems():
  print """
==============================================================================
Origin:      %s
------------------------------------------------------------------------------
Name:        %s
Version:     %s
Revision:    %s
Comment:     ``%s''
Dependants:  %s
Depend stat: %i
""" % (name, port.attr('name'), port.attr('version'), port.attr('revision'),
       port.attr('comment'), port.depends().dependants(fields=True),
       port.depends().status())

print len(ports)
configs = [i for i in ports.itervalues() if i.stage() < Port.CONFIG]
while len(configs):
  for i in configs:
    i.config()
  ports_queue.join()
  print ports_queue.stats(), len(ports)
  configs = [i for i in ports.itervalues() if i.stage() < Port.CONFIG]
